version: "3.1"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: "project"
        user: "1000:1000"
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
    db:
        image: mysql:8.0
        ports: 
            - "3308:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: rootp
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}